services:
  # Bizim Flask uygulamamız
  mlops-app:
    build: .
    container_name: mlops_app_c
    ports:
      - "5003:5000" # Port 5003 olarak kalsın, çakışma olmasın
    volumes:

      - ./app:/app/app
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      - mlflow-server
    networks:
      - mlops-network

  # MLflow Takip Sunucusu
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    container_name: mlflow_server_c
    restart: always
    ports:
      - "5002:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://mlflow-artifacts/

    volumes: # <-- YENİ EKLENEN SATIRLAR
      - mlflow_data:/mlflow
    networks:
      - mlops-network
    depends_on:
      - minio

  # MinIO Depolama Servisi
  minio:
    image: minio/minio:latest
    container_name: minio_c
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge

volumes:
  minio_data:
  mlflow_data: